In [1]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import Ridge
url = "https://raw.githubusercontent.com/H-B-P/d-and-d-sci-sep-2022/main/dset.csv"
df = pd.read_csv(url,index_col=0)
df.columns = ['Intellect','Integrity','Courage','Reflexes','Patience','House','Rating','Year']
url2 = "https://raw.githubusercontent.com/H-B-P/d-and-d-sci-sep-2022/main/incoming_class.csv"
students = pd.read_csv(url2,index_col=0)

A solution to https://www.lesswrong.com/posts/DKDDT8hGCTz8AxBQF/d-and-d-sci-september-2022-the-allocation-helm

In [2]:
print(df)

       Intellect  Integrity  Courage  Reflexes  Patience           House  \
1             64         12       11        45        21      Serpentyne   
2             58         54       15        24        34  Humblescrumble   
3             48         44       32        23        58      Serpentyne   
4             28         28       13        25        67      Serpentyne   
5             33         38       28        28        33    Dragonslayer   
...          ...        ...      ...       ...       ...             ...   
20375         32         31       30        33        28   Thought-Talon   
20376         18         13       32        20        53    Dragonslayer   
20377         54         46       20        39        24   Thought-Talon   
20378         39         61       14        14        24  Humblescrumble   
20379         33         48        2        62        31      Serpentyne   

       Rating  Year  
1          26  1511  
2          40  1511  
3          34  1511  

In [3]:
recent = df[df.Year > 2010]

In [4]:
print(recent)

       Intellect  Integrity  Courage  Reflexes  Patience           House  \
20152          8         50       10        17        10  Humblescrumble   
20153         39         39       25        43        32  Humblescrumble   
20154         63         31       22        63        15  Humblescrumble   
20155         28         28       24        36         8   Thought-Talon   
20156         39         37       24        28         7   Thought-Talon   
...          ...        ...      ...       ...       ...             ...   
20375         32         31       30        33        28   Thought-Talon   
20376         18         13       32        20        53    Dragonslayer   
20377         54         46       20        39        24   Thought-Talon   
20378         39         61       14        14        24  Humblescrumble   
20379         33         48        2        62        31      Serpentyne   

       Rating  Year  
20152      16  2011  
20153      26  2011  
20154      20  2011  

I am given that "for the last decade" allocations are random, and hence the 'recent' dataframe will have no selection effects.

Now, since the data is moderately high-dimensional, I thrash it with a linear regression to see what happens.

In [24]:
PuffR = recent[recent.House=='Humblescrumble']
GriffR = recent[recent.House=='Dragonslayer']
ClawR = recent[recent.House=='Thought-Talon']
SlythR = recent[recent.House=='Serpentyne']

Puff = df[df.House=='Humblescrumble']
Griff = df[df.House=='Dragonslayer']
Claw = df[df.House=='Thought-Talon']
Slyth = df[df.House=='Serpentyne']

In [46]:
PuffPredictors = PuffR[['Intellect','Integrity','Courage','Reflexes','Patience']]
PuffResults = PuffR['Rating']

puff = Ridge(alpha=0.1)
#puff = linear_model.LinearRegression()
puff.fit(PuffPredictors, PuffResults)

# Make predictions using the testing set
PuffPredictions = puff.predict(Puff[['Intellect','Integrity','Courage','Reflexes','Patience']])

# The coefficients
print("Coefficients: \n", puff.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Puff['Rating'], PuffPredictions))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Puff['Rating'], PuffPredictions))

Coefficients: 
 [ 0.12446555  0.3263759   0.00741056 -0.0465382   0.17803888]
Mean squared error: 35.14
Coefficient of determination: 0.47


In [47]:
GriffPredictors = GriffR[['Intellect','Integrity','Courage','Reflexes','Patience']]
GriffResults = GriffR['Rating'] 

griff = Ridge(alpha=0.1)
#griff = linear_model.LinearRegression()
griff.fit(GriffPredictors, GriffResults)

# Make predictions using the testing set
GriffPredictions = griff.predict(Griff[['Intellect','Integrity','Courage','Reflexes','Patience']])

# The coefficients
print("Coefficients: \n", griff.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Griff['Rating'], GriffPredictions))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Griff['Rating'], GriffPredictions))

Coefficients: 
 [0.08800325 0.07668528 0.29141573 0.29281638 0.18630045]
Mean squared error: 62.18
Coefficient of determination: 0.37


In [48]:
ClawPredictors = ClawR[['Intellect','Integrity','Courage','Reflexes','Patience']]
ClawResults = ClawR['Rating'] 

claw = Ridge(alpha=0.1)
#claw = linear_model.LinearRegression()
claw.fit(ClawPredictors, ClawResults)

# Make predictions using the testing set
ClawPredictions = claw.predict(Claw[['Intellect','Integrity','Courage','Reflexes','Patience']])

# The coefficients
print("Coefficients: \n", claw.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Claw['Rating'], ClawPredictions))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Claw['Rating'], ClawPredictions))

Coefficients: 
 [0.3792509  0.07694265 0.13598182 0.2007744  0.36543627]
Mean squared error: 70.17
Coefficient of determination: 0.46


In [49]:
SlythPredictors = SlythR[['Intellect','Integrity','Courage','Reflexes','Patience']]
SlythResults = SlythR['Rating'] 

slyth = Ridge(alpha=0.1)
#slyth = linear_model.LinearRegression()
slyth.fit(SlythPredictors, SlythResults)

# Make predictions using the testing set
SlythPredictions = slyth.predict(Slyth[['Intellect','Integrity','Courage','Reflexes','Patience']])

# The coefficients
print("Coefficients: \n", slyth.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Slyth['Rating'], SlythPredictions))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(Slyth['Rating'], SlythPredictions))

Coefficients: 
 [ 0.28151878  0.04703135 -0.02478481  0.15862298  0.24644294]
Mean squared error: 68.10
Coefficient of determination: 0.26


Observation 1: The full relation is definitely nonlinear.  
Observation 2: The linear model does yield an indication as to which traits are important when giving a student to a specific House;   
Humblescrumbles need primarily Integrity, and to a lesser extent Intelligence and Patience  
Dragonslayers need primarily Courage and Reflexes, and secondarily Patience  
Taloners need primarily Intelligence and Patience, and secondarily Reflexes  
Serpentynes need more or less the same statistics as Taloners, with lower scores across the board.

Finally, I observe that my MSE doesn't get much higher than (8.5)^2 when testing the linear model (trained on 10 years of students) on the whole dataset, and so if any student to be sorted gets a predicted score on one house that is >10 higher than their score in any other house, it's probably their best house.

In [51]:
print(students)

         Intellect  Integrity  Courage  Reflexes  Patience  Year
Student                                                         
A               34         52       46        18        33  2022
B               22         13       19        10        25  2022
C               33         11       18        46        46  2022
D                6         21       47        17        23  2022
E               19         33       38         9        17  2022
F               48          6       33        30        54  2022
G               17         10       39        54        32  2022
H               39         20       52        16         6  2022
I                9         11        6        30        25  2022
J               50         27        7        11        30  2022
K               28         16       35        37        29  2022
L                9         28       23        43        53  2022
M               17         25       36        21        65  2022
N               11       

In [54]:
students['PuffPredict'] = puff.predict(students[['Intellect','Integrity','Courage','Reflexes','Patience']])
students['GriffPredict'] = griff.predict(students[['Intellect','Integrity','Courage','Reflexes','Patience']])
students['ClawPredict'] = claw.predict(students[['Intellect','Integrity','Courage','Reflexes','Patience']])
students['SlythPredict'] = slyth.predict(students[['Intellect','Integrity','Courage','Reflexes','Patience']])

In [56]:
print(students[['PuffPredict','GriffPredict','ClawPredict','SlythPredict']])

         PuffPredict  GriffPredict  ClawPredict  SlythPredict
Student                                                      
A          29.540994     22.048093    23.636822     18.598527
B          14.066657      6.300169     7.883854     10.814741
C          16.839057     21.277118    26.667787     24.727899
D          14.211866     15.342354     6.913420      6.610192
E          18.983806     11.323544     7.744344      8.309734
F          19.354241     23.390318    33.722664     27.777328
G          11.812004     25.646436    19.868535     17.474869
H          15.049783     16.166930    13.618475     11.381203
I          10.768752      7.070679     5.047431     10.555597
J          22.875684      7.565184    19.976250     21.043961
K          15.366771     20.372140    19.448550     17.516983
L          20.823214     22.351422    21.509430     19.896289
M          24.096454     22.407442    26.048571     21.152752
N          13.927553     23.823962    14.562065     14.339359
O       

I hence have some predictions for which houses students should go into based on my linear regression model only.

A: Humblescrumble (by 6)  
B: Humblescrumble (by 3)  
C: Thought-Talon (by 2)  
D: Dragonslayer (by 1)  
E: Humblescrumble (by 7)  
F: Thought-Talon (by 6)  
G: Dragonslayer (by 6)  
H: Dragonslayer (by 2)  
I: Serpentyne (~equal to Humblescrumble)  
J: Humblescrumble (by 1) -- but switch to Serpentyne if balancing class sizes  
K: Dragonslayer (by 1)  
L: Dragonlayer (by 1) -- but switch to Thought-Talon if balancing class sizes  
M: Thought-Talon (by 2)  
N: Dragonlayer (by 9)  
O: Serpentyne (by 1)  
P: Serpentyne (by 1)  
Q: Humblescrumble (by 1) -- but switch to Thought-Talon if balancing class sizes  
R: Humblescrumble (by 5)  
S: Thought-Talon (by 1)  -- but switch to Serpentyne if balancing class sizes  
T: Humblescrumble (by 10).

Now, based on genre of the data format, I consider it likely that I am penalised in some way for assigning students to Houses in non-equal quantities. If so, I change the house assignments of students J,L,Q and S as given above.


Hypothesis; non-equal allocation to houses in a given year makes the year as a whole do worse. Let's test this.